# Basics

In [3]:
import numpy as  np
a=np.array([1,2,3])
print(a)

# get dimensions
a.ndim

[1 2 3]


1

In [5]:
# get shape
a.shape

#get type
a.dtype

dtype('int32')

In [10]:
# data type
b=np.array([1,2,3],dtype="int16")

print(a.size,b.size)
# get size
print(a.itemsize,b.itemsize)

# total size
a.nbytes

3 3
4 2


12

# Operations

In [13]:
a=np.array([[1,2,7,4,5,6,7],[8,9,10,11,12,13,14]])

# ger specific element
a[1,5]

13

In [15]:
# get specific row
a[0,:]

array([1, 2, 7, 4, 5, 6, 7])

In [16]:
#get specific col
a[:,4]

array([ 5, 12])

In [18]:
# a little advance {start:end:stepsize}
a[1,2:6:2]


array([ 9, 11, 13])

In [20]:
# to change
a[1,5]=20
print(a)

a[:,5]=[6,13]
print(a)

[[ 1  2  7  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  7  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# 3D array
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c[0][1][1])

4


# Initializing differnt types of Arrays

In [24]:
# All zeroes matrix
z=np.zeros((2,2,2))
z

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [26]:
# all 1s
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
# any other number
np.full((2,2),11)

array([[11, 11],
       [11, 11]])

In [30]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [31]:
# random numbers
np.random.rand(4,2)

array([[0.01091077, 0.02180827],
       [0.4490978 , 0.78682418],
       [0.30027686, 0.4509749 ],
       [0.62079633, 0.59464236]])

In [33]:
# random integer values 
np.random.randint(20,size=(3,3))

array([[ 2, 12, 15],
       [19,  4, 10],
       [ 8, 13, 18]])

In [34]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
arr=np.array([1,2,3])
r1=np.repeat(arr,4)
print(r1)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [38]:
arr=np.array([[1,2,3]])
r2=np.repeat(arr,3,axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [43]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
print(z)
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
### careful while copying arrays
a=np.array([1,2,3])
b=a
b[0]=100
#changes both a and b
print(a)
print(b)

[100   2   3]
[100   2   3]


In [45]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100

print(a)
print(b)

[1 2 3]
[100   2   3]


# mathematics

In [49]:
a=np.array([1,2,3,4])
print(a+2,a-2,a*2,a/2)

[3 4 5 6] [-1  0  1  2] [2 4 6 8] [0.5 1.  1.5 2. ]


In [50]:
b=np.array([0,0,0,0])
a=np.array([2,2,2,2])
a+b


array([2, 2, 2, 2])

In [51]:
a**2

array([4, 4, 4, 4])

In [54]:
# take sin

np.sin(a)
np.cos(b)

array([1., 1., 1., 1.])